# Welcome to Serverless!
#
# This file is the main config file for our service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: bedrock
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  timeout: 600
  stage: dev
  region: us-east-1
functions:
  generateJokesFunction:
    handler: handler.bedrock
    iamRoleStatements:
      - Effect: Allow
        Action: 'bedrock:*'
        Resource: '*'